language: node_js
node_js:
  - "stable"
sudo: required
services:
  - docker
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - npm run test
  - export REPO=restaurantorder/ro-order-api
  - export COMMIT=latest 
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker run -d $REPO:$COMMIT
  - docker ps -a
after_success:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - gcloud --quiet components update
  # Auth flow
  - echo $GCLOUD_KEY | base64 --decode > gcloud.json
  - gcloud auth activate-service-account $GCLOUD_EMAIL --key-file gcloud.json
  - ssh-keygen -f ~/.ssh/google_compute_engine -N ""
  # Push to Google container registry
  - gcloud docker -- push gcr.io/$CLOUDSDK_CORE_PROJECT/ro-order-api:latest

# after_success:
#   - docker login -u $DOCKER_USER -p $DOCKER_PASS
#   - export TAG=master
#   - docker tag $REPO:$COMMIT $REPO:$TAG
#   - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
#   - docker push $REPO